version: '3'

services:
  notes:
    container_name: notes
    command: bash -c "python3 /notes/manage.py migrate &&
                      daphne -b 0.0.0.0 -p 8000 notes.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - ./notes/:/notes/
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - database

  celery:
    container_name: celery_notes
    build:
      context: .
    command: celery -beat -A notes worker -l info -E
    depends_on:
      - redis

  redis:
    container_name: notes_redis
    image: redis:latest
    ports:
      - "6378:6379"

  database:
    container_name: notes_database
    image: postgres:9.6
    restart: always
    environment:
      LC_AL: "en_US.UTF-8"
      LC_CTYPE: "en_US.UTF-8"
      POSTGRES_PASSWORD: "notes"
      POSTGRES_USER: "notes"
      POSTGRES_DB: "notes"
      PGDATA: "/var/lib/postgresql/data/db"

    ports:
      - "5431:5432"
